
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 09 00:02:54 BOT 2010
//----------------------------------------------------

package Ejemplo1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 7;
  public static final int error = 1;
  public static final int IGUAL = 2;
  public static final int SUMA = 3;
  public static final int PARENTDER = 6;
  public static final int PARENTIZQ = 5;
  public static final int POR = 4;
  public static final int EOF = 0;
}

